### ISSUE TITLE
V2 Checklist

### ISSUE THREAD

**Issue by mia1024** [raxod502/hyperschedule#186]
- [ ] Setup a proper checklist
## Features
- [x] Dark mode
- [x] Schedule minimap
- [x] List of added courses
  - [x] Button to add courses from course list

- [x] Schedule page      
- [ ] "Archive mode" for viewing historical class data
## Filters
- [ ] Negative filters
- [x] Course Areas
- [x] Department
- [x] Campus
- [x] Time range
- [x] Day of week

## Sharing
- [ ] Share course by link 
- [x] Share schedule by link
  - [ ] OpenGraph support with image to schedule
- [x] iCal subscription
